### ISSUE TITLE
Downloaded Podcasts - File Folder location?

### ISSUE THREAD

**Issue by Joihnny579** [podverse/podverse-fdroid#131]
Hello.

Where are downloaded Podcasts stored (on Android). Wanted to export a download the other day to listen on another device, and could not find the file. 

Would be nice to maybe even have a share-button for the downloaded file (not the link to the stream). Possible?

Thanks.

**Comment by mitchdowney** [comment]
Hi @Joihnny579 I'm sorry, to be honest, I struggle with understanding the Android file system, and will need help from open source contributors in order to give definitive answers to this. No one on our core dev team really understands Android. We mainly know JavaScript and iOS.

Also, if you have questions about the F-Droid mobile app, please use this repo: https://github.com/podverse/podverse-rn We try to consolidate our discussion over there, since the 2 repos are identical, except the F-Droid version has some 3rd party libraries removed.

**Comment by mitchdowney** [comment]
@Joihnny579 I'm going to close this issue. If you'd like to continue discussion, can re-open the issue over in the podverse-rn repo?
