### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [podverse/podverse-fdroid#15]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text in the red box is half blocked. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display.
![297165ECE247F4EDC808C49B7E0633F7](https://user-images.githubusercontent.com/18572115/103166828-d73b9a80-4860-11eb-8c70-41b3da82a9e1.png)

App version is 2.10.1, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="445" alt="bug-podverse-2" src="https://user-images.githubusercontent.com/18572115/103166826-d276e680-4860-11eb-885e-6634965cd7fd.png">

**Comment by mitchdowney** [comment]
@franklinbill I'm sorry for the late reply! We have been very busy working on a new major release (Podverse 3.0), and the layout for the filter buttons will change significantly. Before it is released we will test the app with the maximum font size turned out and hopefully fix all visual issues.

Thanks so much for reporting this issue and your kind feedback :)

**Comment by mitchdowney** [comment]
I think the duplicate dropdown carets were fixed a long time ago...
