### ISSUE TITLE
Podcasts from the future

### ISSUE THREAD

**Issue by 2br-2b** [podverse/podverse-fdroid#17]
Hello!

Thank you so much for for making the Podverse app! I use it all of the time for my podcasts!

When listing all podcasts sorted by most recent, I get some times travelers' podcasts coming up:

![Screenshot_20210117-212758](https://user-images.githubusercontent.com/43968991/104869309-a02b4700-593d-11eb-8794-fa419ca31286.png)

As much as we'd all like to know the future, since this knowledge should not be known by mere mortals, these podcasts should probably be removed :-)

**Comment by mitchdowney** [comment]
Haha thanks for reporting! Agreed this knowledge is too powerful, and we have already addressed this in the latest iOS and Android version. The F-Droid release is a version behind however, so they're still appearing there.

We expect to have our big Podverse 3.0 release by the end of the month on all platforms, and this bug should be fixed in it.

**Comment by 2br-2b** [comment]
Glad to hear that! Thank you so much for your hard work!

**Comment by mitchdowney** [comment]
This bug should no longer appear as we removed sorting All Podcasts by Most Recent a long time ago.
